- name: test playbook
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - paloaltonetworks.panos
  vars:
     provider: 
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"
  # roles:
  #   - role: PaloAltoNetworks.paloaltonetworks
  tasks:
    - name: Create object 'Test'
      panos_address_object:
        provider: "{{ provider }}"
        name: "{{item.name}}"
        value: "{{item.ip_address}}"
        description: "{{item.description}}"
      loop: "{{ objects }}"

    - name: Edit object group 'Blacklist'
      panos_address_group:
        provider: "{{ provider }}"
        name: 'Blacklist'
        static_value: ["{{item.name}}"]
        state: "merged"
      loop: "{{ objects }}"
     
    - name: commit candidate config on panorama
      panos_commit_panorama:
        provider: '{{ provider }}'
        description: 'object added'

    - name: wait for commits to finish
      panos_check:
        provider: '{{ provider }}'
        initial_delay: 10
        interval: 5
        timeout: 100
