- name: test playbook
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - paloaltonetworks.panos
  vars:
     provider: 
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"
  # roles:
  #   - role: PaloAltoNetworks.paloaltonetworks
  tasks:
    - name: Create object 'Test'
      panos_address_object:
        provider: "{{ provider }}"
        name: "{{objects.name}}"
        value: "{{objects.ip_address}}"
        description: "{{objects.description}}"

    - name: Edit object group 'Blacklist'
      panos_address_group:
        provider: "{{ provider }}"
        name: 'Blacklist'
        static_value: ["{{objects.name}}"]
        state: "merged"
      #loop: "{{ objects }}"