- name: test playbook
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - paloaltonetworks.panos
  # roles:
  #   - role: PaloAltoNetworks.paloaltonetworks
  tasks:
    - name: Get the system info
      panos_op:
         provider:
            ip_address: "{{ ip_address }}"
            username: "{{ username }}"
            password: "{{ password }}"
         cmd: 'show system info'
      register: res

    - debug:
        var: res.stdout
    - name: Create object group 'SI'
      panos_address_group:
        provider:
            ip_address: "{{ ip_address }}"
            username: "{{ username }}"
            password: "{{ password }}"
        name: 'SI'
        dynamic_value: "'SI_Instances5'"
        tag: ['SI']

