- name: test playbook
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - paloaltonetworks.panos
  # roles:
  #   - role: PaloAltoNetworks.paloaltonetworks
  tasks:
    - name: Get the system info
      panos_op:
         provider:
            ip_address: "{{ ip_address }}"
            username: "{{ username }}"
            password: "{{ password }}"
         cmd: 'show system info'
      register: res

    - debug:
        var: res.stdout

    - name: Create object 'Test-One'
      panos_address_object:
        provider: '{{ provider }}'
        name: 'Test-One'
        value: '192.168.0.98'
        description: 'Machine A'
        
    - name: Create object 'Test-Two'
      panos_address_object:
        provider: '{{ provider }}'
        name: 'Test-Two'
        value: '192.168.0.99'
        description: 'Machine B'

    - name: Edit object group 'Blacklist'
      panos_address_group:
        provider:
            ip_address: "{{ ip_address }}"
            username: "{{ username }}"
            password: "{{ password }}"
        name: 'Blacklist'
        static_value: ['Test-One', 'Test-Two']

