- name: test playbook
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - paloaltonetworks.panos
  # roles:
  #   - role: PaloAltoNetworks.paloaltonetworks
  tasks:
    - name: Get the system info
      panos_op:
         provider:
            ip_address: "{{ ip_address }}"
            username: "{{ username }}"
            password: "{{ password }}"
         cmd: 'show system info'
      register: res

    - debug:
        var: res.stdout
    - name: Create service group 'Prod-Services'
      panos_service_group:
        provider: '{{ provider }}'
        name: 'Prod-Services'
        value: ['ssh-tcp-22', 'mysql-tcp-3306']

