- name: test playbook
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - paloaltonetworks.panos
  # roles:
  #   - role: PaloAltoNetworks.paloaltonetworks
  tasks:
    - name: Get the system info
      panos_op:
         provider: 
            provider:
              ip_address: "192.168.0.10"
              username: "{{ username }}"
              password: "{{ password }}"
         cmd: 'show system info'
      register: res

    - debug:
        var: res.stdout

