- name: test playbook
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - paloaltonetworks.panos
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.8
  # roles:
  #   - role: PaloAltoNetworks.paloaltonetworks
  tasks:
    - name: Get the system info
      panos_op:
         provider: "{{ provider }}"
         cmd: 'show system info'
      register: res

    - debug:
        var: res

