- name: test playbook
  hosts: host
  collections:
    - paloaltonetworks.panos
  roles:
    - role: PaloAltoNetworks.paloaltonetworks
  tasks:
  - name: Get the system info
    panos_op:
      provider: '{{ provider }}'
      cmd: 'show system info'
    register: res

  - debug:
      msg: '{{ res.stdout }}'

